spring:
  application:
    name: server
  datasource:
    url: jdbc:mysql://localhost:3306/khuthondb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: khureka
    password: khureka
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
