spring:
  application:
    name: server
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/${MYSQL_DATABASE}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  secret: ${JWT_SECRET}
  access-token-validity-in-seconds: 3600

ncp:
  maps:
    client-id: ${NCP_MAPS_CLIENT_ID}

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket: khuthon-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false